services:
  nginx:
    image: nginx:1.27-alpine
    container_name: lab6_nginx
    ports:
      - "8080:80"
    volumes:
      - ./www:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - php

  php:
    build: .
    container_name: lab6_php
    volumes:
      - ./www:/var/www/html
    expose:
      - "9000"
    depends_on:
      - clickhouse
    networks:
      - default_network


  clickhouse:
    image: clickhouse/clickhouse-server
    container_name: lab6_clickhouse
    ports:
      - "8123:8123"
      - "9000:9000"
    volumes:
      - clickhouse_data:/var/lib/clickhouse
    networks:
      - default_network


networks:
 default_network:
   driver: bridge

# Чтобы сохранялось между перезапусками
volumes:
  clickhouse_data: